/**
 * Sidebars configuration for the folder-based docs structure.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  arquitecturaSidebar: [{ type: 'autogenerated', dirName: 'arquitectura' }],
  backendSidebar: [{ type: 'autogenerated', dirName: 'backend' }],
  frontendSidebar: [{ type: 'autogenerated', dirName: 'frontend' }],
  devopsSidebar: [{ type: 'autogenerated', dirName: 'devops' }],
  databaseSidebar: [{ type: 'autogenerated', dirName: 'database' }],
  gobernanzaSidebar: [{ type: 'autogenerated', dirName: 'gobernanza' }],
};

module.exports = sidebars;
